name: riddlepedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  webview_flutter: ^4.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11
  material_symbols_icons: ^4.2741.0
  flutter_rating_bar: ^4.0.1
  supabase_flutter: ^2.0.0
  flutter_facebook_auth: ^6.0.4
  loading_animation_widget: ^1.2.1
  pull_to_refresh_flutter3: ^2.0.2
  logger: ^2.3.0
  flutter_dialogs: ^3.0.0
  awesome_dialog: ^3.2.1
  flutter_easyloading: ^3.0.5
  intl: ^0.17.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#38B6FF"
  color_ios: "#38B6FF"
  color_dark_ios: "#38B6FF"
  image_ios: assets/icon/app_icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/image/cyborg.jpg
    - assets/image/facebook_logo.png
    - assets/image/google_logo.png
